// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantNode.DataAccess.Contexts;

#nullable disable

namespace PlantNode.DataAccess.Migrations
{
    [DbContext(typeof(PlantNodeDbContext))]
    [Migration("20260702145355_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlantNode.Domain.Entities.Machines.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Machines", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Machine");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PlantNode.Domain.Entities.Plants.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Plants", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Plant");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PlantNode.Domain.Enums.MachineStatusLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MachineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineStatusLogs");
                });

            modelBuilder.Entity("PlantNode.Domain.Entities.Machines.CoilWindingMachine", b =>
                {
                    b.HasBaseType("PlantNode.Domain.Entities.Machines.Machine");

                    b.Property<int>("CurrentTurnCount")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxCoilDiameter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxRpm")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxWireDiameter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinWireDiameter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SpindleCount")
                        .HasColumnType("int");

                    b.Property<float>("TargetSpeed")
                        .HasColumnType("real");

                    b.Property<int>("TargetTurnCount")
                        .HasColumnType("int");

                    b.Property<decimal>("WireTension")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("CoilWindingMachine");
                });

            modelBuilder.Entity("PlantNode.Domain.Entities.Plants.CoilWindingPlant", b =>
                {
                    b.HasBaseType("PlantNode.Domain.Entities.Plants.Plant");

                    b.Property<int>("MaxAnnealingTemperatureCelsius")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxSupportedWireGauge")
                        .HasColumnType("decimal(18,4)");

                    b.HasDiscriminator().HasValue("CoilWindingPlant");
                });

            modelBuilder.Entity("PlantNode.Domain.Entities.Machines.Machine", b =>
                {
                    b.HasOne("PlantNode.Domain.Entities.Plants.Plant", "Plant")
                        .WithMany("Machines")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantNode.Domain.Enums.MachineStatusLog", b =>
                {
                    b.HasOne("PlantNode.Domain.Entities.Machines.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("PlantNode.Domain.Entities.Plants.Plant", b =>
                {
                    b.Navigation("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
